// Generated by `tools/theme/quantised.mjs` — do not edit by hand (C10 I41).
// Regenerate with `make quantised` after a shipped theme changes; T3.73 is red until you do.
// 14 sets over 3 themes: each theme's surfaces and each of its palettes.
export const QUANTISED: Readonly<Record<string, Readonly<Record<string, number>>>> = Object.freeze({
  // light.palettes.spectrum
  "[[\"0\",\"#e45649\"],[\"1\",\"#d19a66\"],[\"2\",\"#c18401\"],[\"3\",\"#50a14f\"],[\"4\",\"#0997b3\"],[\"5\",\"#0184bc\"],[\"6\",\"#4078f2\"],[\"7\",\"#a626a4\"],[\"outline\",\"#383a42\"]]": Object.freeze({ "0": 203, "1": 180, "2": 172, "3": 71, "4": 31, "5": 31, "6": 26, "7": 90, "outline": 237 }),
  // dark.palettes.spectrum
  "[[\"0\",\"#e8736b\"],[\"1\",\"#e89866\"],[\"2\",\"#e8c95e\"],[\"3\",\"#a3d066\"],[\"4\",\"#66c890\"],[\"5\",\"#5fb5d4\"],[\"6\",\"#7a8fe0\"],[\"7\",\"#c187d4\"],[\"outline\",\"#e8e8e8\"]]": Object.freeze({ "0": 167, "1": 173, "2": 221, "3": 149, "4": 79, "5": 74, "6": 68, "7": 140, "outline": 254 }),
  // high-contrast.palettes.spectrum
  "[[\"0\",\"#ff7171\"],[\"1\",\"#f87c00\"],[\"2\",\"#c99700\"],[\"3\",\"#0ab827\"],[\"4\",\"#0eb2a5\"],[\"5\",\"#2ea5fa\"],[\"6\",\"#b887fc\"],[\"7\",\"#eb68f7\"],[\"outline\",\"#ffffff\"]]": Object.freeze({ "0": 203, "1": 208, "2": 136, "3": 34, "4": 37, "5": 75, "6": 141, "7": 207, "outline": 231 }),
  // light.palettes.tone
  "[[\"accent\",\"#1f60f0\"],[\"default\",\"#383a42\"],[\"dim\",\"#696c77\"],[\"error\",\"#a81f12\"],[\"identifier\",\"#07768c\"],[\"info\",\"#0173a5\"],[\"meta\",\"#a626a4\"],[\"muted\",\"#94959c\"],[\"ok\",\"#3c793c\"],[\"warn\",\"#916301\"]]": Object.freeze({ "default": 237, "error": 88, "meta": 90, "identifier": 31, "warn": 94, "accent": 27, "ok": 65, "info": 24, "dim": 242, "muted": 246 }),
  // high-contrast.palettes.tone
  "[[\"accent\",\"#b887fc\"],[\"default\",\"#ffffff\"],[\"dim\",\"#c7c7c7\"],[\"error\",\"#ff7171\"],[\"identifier\",\"#0eb2a5\"],[\"info\",\"#2ea5fa\"],[\"meta\",\"#eb68f7\"],[\"muted\",\"#9f9f9f\"],[\"ok\",\"#0ab827\"],[\"warn\",\"#c99700\"]]": Object.freeze({ "error": 203, "meta": 207, "info": 75, "ok": 34, "accent": 141, "warn": 136, "identifier": 37, "muted": 247, "dim": 251, "default": 231 }),
  // dark.palettes.tone
  "[[\"accent\",\"#e8a87c\"],[\"default\",\"#d4d4d4\"],[\"dim\",\"#8a8a8a\"],[\"error\",\"#c62828\"],[\"identifier\",\"#7fb8b8\"],[\"info\",\"#7faecf\"],[\"meta\",\"#b89cd2\"],[\"muted\",\"#626262\"],[\"ok\",\"#87b86c\"],[\"warn\",\"#d4b35a\"]]": Object.freeze({ "muted": 241, "error": 124, "dim": 245, "meta": 139, "info": 74, "ok": 107, "identifier": 109, "accent": 216, "warn": 179, "default": 188 }),
  // high-contrast.surfaces
  "[[\"bg\",\"#000000\"],[\"bgDeep\",\"#1c1c1c\"],[\"bgElev\",\"#121212\"],[\"border\",\"#767676\"],[\"borderStrong\",\"#a6a6a6\"],[\"diffAdd\",\"#003300\"],[\"diffRemove\",\"#3b0000\"],[\"errorGround\",\"#ff7171\"],[\"errorInk\",\"#3d0000\"],[\"selection\",\"#00405c\"]]": Object.freeze({ "bg": 16, "bgElev": 233, "diffRemove": 52, "errorInk": 52, "bgDeep": 234, "diffAdd": 22, "selection": 24, "border": 243, "errorGround": 203, "borderStrong": 248 }),
  // dark.surfaces
  "[[\"bg\",\"#1a1a1a\"],[\"bgDeep\",\"#141414\"],[\"bgElev\",\"#222222\"],[\"border\",\"#2c2c2c\"],[\"borderStrong\",\"#3a3a3a\"],[\"diffAdd\",\"#002600\"],[\"diffRemove\",\"#490000\"],[\"errorGround\",\"#c62828\"],[\"errorInk\",\"#ffffff\"],[\"selection\",\"#264057\"]]": Object.freeze({ "bgDeep": 233, "bg": 234, "diffAdd": 234, "diffRemove": 52, "bgElev": 235, "border": 236, "borderStrong": 237, "selection": 237, "errorGround": 124, "errorInk": 231 }),
  // light.surfaces
  "[[\"bg\",\"#fafafa\"],[\"bgDeep\",\"#e8e8e8\"],[\"bgElev\",\"#f0f0f0\"],[\"border\",\"#d3d3d3\"],[\"borderStrong\",\"#c8c8c8\"],[\"diffAdd\",\"#d2ffd2\"],[\"diffRemove\",\"#fff0f0\"],[\"errorGround\",\"#a81f12\"],[\"errorInk\",\"#ffffff\"],[\"selection\",\"#c9ddf5\"]]": Object.freeze({ "errorGround": 124, "borderStrong": 251, "border": 252, "selection": 153, "bgDeep": 254, "bgElev": 255, "diffRemove": 255, "diffAdd": 194, "bg": 231, "errorInk": 231 }),
  // light.palettes.categorical
  "[[\"c1\",\"#8a5f00\"],[\"c2\",\"#00688f\"],[\"c3\",\"#00674a\"],[\"c4\",\"#7a6a00\"],[\"c5\",\"#0043a8\"],[\"c6\",\"#9c3b00\"],[\"c7\",\"#8f3f6d\"],[\"c8\",\"#4a4a4a\"]]": Object.freeze({ "c5": 26, "c8": 239, "c3": 29, "c6": 130, "c7": 132, "c2": 31, "c1": 136, "c4": 100 }),
  // dark.palettes.categorical, high-contrast.palettes.categorical
  "[[\"c1\",\"#e69f00\"],[\"c2\",\"#56b4e9\"],[\"c3\",\"#3cbf9a\"],[\"c4\",\"#f0e442\"],[\"c5\",\"#8fa8ff\"],[\"c6\",\"#f07a3c\"],[\"c7\",\"#e4a3c4\"],[\"c8\",\"#cfcfcf\"]]": Object.freeze({ "c6": 166, "c2": 74, "c3": 36, "c5": 111, "c1": 214, "c7": 218, "c8": 252, "c4": 227 }),
  // dark.palettes.syntax
  "[[\"comment\",\"#676e7d\"],[\"function\",\"#61afef\"],[\"key\",\"#e06c75\"],[\"keyword\",\"#c678dd\"],[\"number\",\"#d19a66\"],[\"operator\",\"#56b6c2\"],[\"punctuation\",\"#abb2bf\"],[\"string\",\"#98c379\"],[\"type\",\"#e5c07b\"]]": Object.freeze({ "comment": 242, "key": 167, "keyword": 170, "number": 173, "operator": 73, "function": 75, "punctuation": 249, "string": 150, "type": 222 }),
  // light.palettes.syntax
  "[[\"comment\",\"#86888f\"],[\"function\",\"#1f60f0\"],[\"key\",\"#a8432c\"],[\"keyword\",\"#a626a4\"],[\"number\",\"#916301\"],[\"operator\",\"#0173a5\"],[\"punctuation\",\"#383a42\"],[\"string\",\"#3c793c\"],[\"type\",\"#7a5401\"]]": Object.freeze({ "punctuation": 237, "type": 94, "keyword": 90, "key": 94, "number": 94, "function": 27, "string": 65, "operator": 31, "comment": 102 }),
  // high-contrast.palettes.syntax
  "[[\"comment\",\"#9f9f9f\"],[\"function\",\"#5fa0fb\"],[\"key\",\"#fb7289\"],[\"keyword\",\"#e46dfb\"],[\"number\",\"#f87c00\"],[\"operator\",\"#0aafbe\"],[\"punctuation\",\"#d7d7d7\"],[\"string\",\"#0fb80f\"],[\"type\",\"#bb9c00\"]]": Object.freeze({ "type": 136, "key": 204, "number": 208, "keyword": 171, "string": 34, "operator": 37, "function": 75, "comment": 247, "punctuation": 188 }),
});
