// Generated by `tools/theme/from-registry.mjs` — do not edit by hand.
// Regenerate with `make themes` after the design registry changes.
//
// 10 themes, projected from `docs/design/language/calcium-registry.json`.
// The registry is normative for these values (R-THM-001); this file is a projection
// of it, and a hand edit here is a value the design does not hold.

import { DARK } from "./tokens-dark.js";
import { HIGH_CONTRAST } from "./tokens-high-contrast.js";
import { LIGHT } from "./tokens-light.js";
import type { MonoClass, PaletteSpec, ThemeSet, ThemeTokens } from "./types.js";

/**
 * A lender's palette, by name. `palettes` is an open record, so a bare lookup is
 * `| undefined` — and a missing palette here is a build-time fact worth throwing
 * on rather than a value worth defaulting, since the theme it would produce is the
 * one C10 I30 exists to refuse.
 */
const lend = (tokens: ThemeTokens, family: string): PaletteSpec => {
  const palette = tokens.palettes[family];
  if (palette === undefined) {
    throw new Error(`${tokens.name} declares no ${family} palette to lend`);
  }
  return palette;
};

/**
 * A lender's per-slot typographic classes (C10 I15). Separate from `lend` because
 * `classes` is optional under `exactOptionalPropertyTypes`, so passing the lookup
 * through unchecked would offer `undefined` to a property that does not accept it —
 * and a "meaning" palette without classes carries nothing at 1-bit, which is a
 * theme worth refusing at build time rather than shipping.
 */
const classesOf = (tokens: ThemeTokens, family: string): Readonly<Record<string, MonoClass>> => {
  const classes = lend(tokens, family).classes;
  if (classes === undefined) {
    throw new Error(`${tokens.name}'s ${family} palette declares no classes to lend`);
  }
  return classes;
};

export const REGISTRY_THEMES: ThemeSet = Object.freeze({
  "dark": Object.freeze({
    name: "Dark",
    variant: "dark",
    background: "terminal",
    surfaces: Object.freeze({
      "bg": "#1a1a1a",
      "bgElev": "#222222",
      "bgDeep": "#141414",
      "selection": "#264057",
      "meterFill": "#315a34",
      "border": "#2c2c2c",
      "borderStrong": "#3a3a3a",
      "diffAdd": "#002600",
      "diffRemove": "#490000",
      "errorGround": "#c62828",
      "mAuto": "#6b5a1f",
      "mAccept": "#4a3a63",
      "mPlan": "#2a4a63",
      "mManual": "#3a3a3a",
      "skipGround": "#7a1414",
      "focusGround": "#2e2e2e",
      "errorInk": "#ffffff",
      "mInk": "#f2eede",
      "skipInk": "#ffe8e8",
      "pick": "#e8a87c",
      "pickInk": "#000000",
      "link": "#7fb8b8",
      "linkInk": "#000000",
      "chosen": "#87b86c",
      "chosenInk": "#000000",
    }),
    palettes: Object.freeze({
      tone: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "default": "#d4d4d4",
          "dim": "#8a8a8a",
          "muted": "#8c8c8c",
          "ok": "#87b86c",
          "warn": "#d4b35a",
          "error": "#f05a5a",
          "info": "#7faecf",
          "accent": "#e8a87c",
          "meta": "#b89cd2",
          "identifier": "#7fb8b8",
        }),
        // The 1-bit typographic fallback per slot (C10 I15). The registry carries
        // no such record, and a tone that resolves to nothing at 1-bit carries
        // nothing — so DARK's classes stand, as with the palettes below.
        classes: classesOf(DARK, "tone"),
      }),
      // dark is a theme this repository already measured against these
      // floors; the registry carries no syntax or categorical tokens to match.
      categorical: lend(DARK, "categorical"),
      syntax: lend(DARK, "syntax"),
      spectrum: lend(DARK, "spectrum"),
    }),
    fourBit: DARK.fourBit,
    composed: Object.freeze({
      ...(DARK.composed ?? {}),
      "surface.focusGround": Object.freeze({
        ...(DARK.composed?.["surface.focusGround"] ?? {}),
        "tone.dim": "#9e9e9e",
        "tone.error": "#fa6464",
        "tone.muted": "#969696",
      }),
      "surface.selection": Object.freeze({
        ...(DARK.composed?.["surface.selection"] ?? {}),
        "tone.dim": "#bdbdbd",
        "tone.error": "#ff9b91",
        "tone.meta": "#ddc1ee",
        "tone.muted": "#bdbdbd",
      }),
    }),
  }),
  "light": Object.freeze({
    name: "Light",
    variant: "light",
    background: "surface",
    surfaces: Object.freeze({
      "bg": "#fafafa",
      "bgElev": "#f0f0f0",
      "bgDeep": "#e8e8e8",
      "selection": "#c9ddf5",
      "meterFill": "#c6e2bd",
      "border": "#d3d3d3",
      "borderStrong": "#c8c8c8",
      "diffAdd": "#d2ffd2",
      "diffRemove": "#fff0f0",
      "errorGround": "#a81f12",
      "mAuto": "#f4e3ae",
      "mAccept": "#e8d4ee",
      "mPlan": "#cfe4f5",
      "mManual": "#e0e0e0",
      "skipGround": "#8f1a10",
      "focusGround": "#e2e2e2",
      "errorInk": "#ffffff",
      "mInk": "#2a2622",
      "skipInk": "#fff2f0",
      "pick": "#1f60f0",
      "pickInk": "#ffffff",
      "link": "#07768c",
      "linkInk": "#ffffff",
      "chosen": "#3c793c",
      "chosenInk": "#ffffff",
    }),
    palettes: Object.freeze({
      tone: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "default": "#383a42",
          "dim": "#696c77",
          "muted": "#6e6f76",
          "ok": "#3c793c",
          "warn": "#916301",
          "error": "#c21f10",
          "info": "#0173a5",
          "accent": "#1f60f0",
          "meta": "#a626a4",
          "identifier": "#07768c",
        }),
        // The 1-bit typographic fallback per slot (C10 I15). The registry carries
        // no such record, and a tone that resolves to nothing at 1-bit carries
        // nothing — so LIGHT's classes stand, as with the palettes below.
        classes: classesOf(LIGHT, "tone"),
      }),
      // light is a theme this repository already measured against these
      // floors; the registry carries no syntax or categorical tokens to match.
      categorical: lend(LIGHT, "categorical"),
      syntax: lend(LIGHT, "syntax"),
      spectrum: lend(LIGHT, "spectrum"),
    }),
    fourBit: LIGHT.fourBit,
    composed: Object.freeze({
      ...(LIGHT.composed ?? {}),
      "surface.bgDeep": Object.freeze({
        ...(LIGHT.composed?.["surface.bgDeep"] ?? {}),
        "tone.accent": "#1556e6",
        "tone.dim": "#5f626d",
        "tone.identifier": "#006c82",
        "tone.info": "#00699b",
        "tone.muted": "#64656c",
        "tone.ok": "#326f32",
        "tone.warn": "#875900",
      }),
      "surface.bgElev": Object.freeze({
        ...(LIGHT.composed?.["surface.bgElev"] ?? {}),
        "tone.muted": "#64656c",
      }),
      "surface.focusGround": Object.freeze({
        ...(LIGHT.composed?.["surface.focusGround"] ?? {}),
        "tone.accent": "#1556e6",
        "tone.dim": "#5f626d",
        "tone.identifier": "#006c82",
        "tone.info": "#00699b",
        "tone.muted": "#5a5b62",
        "tone.ok": "#326f32",
        "tone.warn": "#875900",
      }),
      "surface.selection": Object.freeze({
        ...(LIGHT.composed?.["surface.selection"] ?? {}),
        "tone.accent": "#1747b8",
        "tone.dim": "#4e515b",
        "tone.error": "#a1190d",
        "tone.identifier": "#00576b",
        "tone.info": "#005c8a",
        "tone.meta": "#81207f",
        "tone.muted": "#4e515b",
        "tone.ok": "#205c20",
        "tone.warn": "#704800",
      }),
    }),
  }),
  "hcDark": Object.freeze({
    name: "HC dark",
    variant: "dark",
    background: "surface",
    floor: 7,
    surfaces: Object.freeze({
      "bg": "#000000",
      "bgElev": "#121212",
      "bgDeep": "#1c1c1c",
      "selection": "#efc51c",
      "meterFill": "#005f16",
      "border": "#767676",
      "borderStrong": "#a6a6a6",
      "diffAdd": "#003c00",
      "diffRemove": "#4a0000",
      "errorGround": "#ff7171",
      "mAuto": "#c99700",
      "mAccept": "#b887fc",
      "mPlan": "#2ea5fa",
      "mManual": "#9f9f9f",
      "skipGround": "#ff3b3b",
      "focusGround": "#234f92",
      "errorInk": "#000000",
      "mInk": "#000000",
      "skipInk": "#000000",
      "pick": "#b887fc",
      "pickInk": "#000000",
      "link": "#0eb2a5",
      "linkInk": "#000000",
      "chosen": "#0ab827",
      "chosenInk": "#000000",
    }),
    palettes: Object.freeze({
      tone: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "default": "#ffffff",
          "dim": "#c7c7c7",
          "muted": "#9f9f9f",
          "ok": "#0ab827",
          "warn": "#c99700",
          "error": "#ff7171",
          "info": "#2ea5fa",
          "accent": "#b887fc",
          "meta": "#eb68f7",
          "identifier": "#0eb2a5",
        }),
        // The 1-bit typographic fallback per slot (C10 I15). The registry carries
        // no such record, and a tone that resolves to nothing at 1-bit carries
        // nothing — so DARK's classes stand, as with the palettes below.
        classes: classesOf(DARK, "tone"),
      }),
      // hcDark is a theme this repository already measured against these
      // floors; the registry carries no syntax or categorical tokens to match.
      categorical: lend(HIGH_CONTRAST, "categorical"),
      syntax: lend(HIGH_CONTRAST, "syntax"),
      spectrum: lend(DARK, "spectrum"),
    }),
    fourBit: HIGH_CONTRAST.fourBit,
    bandInk: Object.freeze({
      "focusGround": "#ffffff",
      "selection": "#000000",
    }),
    composed: Object.freeze({
      ...(HIGH_CONTRAST.composed ?? {}),

    }),
  }),
  "hcLight": Object.freeze({
    name: "HC light",
    variant: "light",
    background: "surface",
    floor: 7,
    surfaces: Object.freeze({
      "bg": "#ffffff",
      "bgElev": "#ebebeb",
      "bgDeep": "#dadada",
      "selection": "#46176d",
      "meterFill": "#b5dbad",
      "border": "#000000",
      "borderStrong": "#000000",
      "diffAdd": "#c4f2c4",
      "diffRemove": "#ffd2d2",
      "errorGround": "#a80000",
      "mAuto": "#6b4200",
      "mAccept": "#5b00a8",
      "mPlan": "#003d8f",
      "mManual": "#3a3a3a",
      "skipGround": "#a80000",
      "focusGround": "#7face3",
      "errorInk": "#ffffff",
      "mInk": "#ffffff",
      "skipInk": "#ffffff",
      "pick": "#5b00a8",
      "pickInk": "#ffffff",
      "link": "#00595e",
      "linkInk": "#ffffff",
      "chosen": "#005c00",
      "chosenInk": "#ffffff",
    }),
    palettes: Object.freeze({
      tone: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "default": "#000000",
          "dim": "#2b2b2b",
          "muted": "#525252",
          "ok": "#005c00",
          "warn": "#6b4200",
          "error": "#a80000",
          "info": "#003d8f",
          "accent": "#5b00a8",
          "meta": "#8a006e",
          "identifier": "#00595e",
        }),
        // The 1-bit typographic fallback per slot (C10 I15). The registry carries
        // no such record, and a tone that resolves to nothing at 1-bit carries
        // nothing — so LIGHT's classes stand, as with the palettes below.
        classes: classesOf(LIGHT, "tone"),
      }),
      // Derived from this theme's own registry tones — see SYNTAX_FROM_TONE.
      categorical: Object.freeze({
        carries: "decoration",
        monochrome: "foreground",
        slots: Object.freeze({
          "c1": "#003d8f", // info
          "c2": "#005c00", // ok
          "c3": "#6b4200", // warn
          "c4": "#8a006e", // meta
          "c5": "#00595e", // identifier
          "c6": "#5b00a8", // accent
          "c7": "#a80000", // error
          "c8": "#2b2b2b", // dim
        }),
      }),
      syntax: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "keyword": "#8a006e", // meta
          "string": "#005c00", // ok
          "comment": "#525252", // muted
          "number": "#6b4200", // warn
          "key": "#a80000", // error
          "type": "#5b00a8", // accent
          "function": "#003d8f", // info
          "operator": "#00595e", // identifier
          "punctuation": "#2b2b2b", // dim
        }),
        classes: classesOf(LIGHT, "syntax"),
      }),
      spectrum: lend(LIGHT, "spectrum"),
    }),
    fourBit: LIGHT.fourBit,
    bandInk: Object.freeze({
      "focusGround": "#000000",
      "selection": "#ffffff",
    }),
    composed: Object.freeze({
      "surface.bgElev": Object.freeze({
        "categorical.c2": "#005b00",
        "categorical.c5": "#00575b",
        "categorical.c7": "#a10000",
        "syntax.comment": "#4d4d4d",
        "syntax.key": "#a10000",
        "syntax.operator": "#00575b",
        "syntax.string": "#005b00",
        "tone.error": "#a10000",
        "tone.identifier": "#00575b",
        "tone.muted": "#4d4d4d",
        "tone.ok": "#005b00",
      }),
    }),
  }),
  "ink": Object.freeze({
    name: "Ink",
    variant: "dark",
    background: "terminal",
    surfaces: Object.freeze({
      "bg": "#14181d",
      "bgElev": "#1c2128",
      "bgDeep": "#0f1317",
      "selection": "#1f3a52",
      "meterFill": "#2f5636",
      "border": "#2b323b",
      "borderStrong": "#3c4552",
      "diffAdd": "#0a2a12",
      "diffRemove": "#3d1218",
      "errorGround": "#c94f4f",
      "mAuto": "#6b5522",
      "mAccept": "#4a3566",
      "mPlan": "#234a6b",
      "mManual": "#333b45",
      "skipGround": "#7a2020",
      "focusGround": "#242c35",
      "errorInk": "#000000",
      "mInk": "#f0f4f8",
      "skipInk": "#ffeaea",
      "pick": "#f0883e",
      "pickInk": "#000000",
      "link": "#56cfcf",
      "linkInk": "#000000",
      "chosen": "#6fbf73",
      "chosenInk": "#000000",
    }),
    palettes: Object.freeze({
      tone: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "default": "#c9d1d9",
          "dim": "#8b949e",
          "muted": "#7d8794",
          "ok": "#6fbf73",
          "warn": "#d2a24c",
          "error": "#ff8585",
          "info": "#6cb6ff",
          "accent": "#f0883e",
          "meta": "#b083f0",
          "identifier": "#56cfcf",
        }),
        // The 1-bit typographic fallback per slot (C10 I15). The registry carries
        // no such record, and a tone that resolves to nothing at 1-bit carries
        // nothing — so DARK's classes stand, as with the palettes below.
        classes: classesOf(DARK, "tone"),
      }),
      // Derived from this theme's own registry tones — see SYNTAX_FROM_TONE.
      categorical: Object.freeze({
        carries: "decoration",
        monochrome: "foreground",
        slots: Object.freeze({
          "c1": "#6cb6ff", // info
          "c2": "#6fbf73", // ok
          "c3": "#d2a24c", // warn
          "c4": "#b083f0", // meta
          "c5": "#56cfcf", // identifier
          "c6": "#f0883e", // accent
          "c7": "#ff8585", // error
          "c8": "#8b949e", // dim
        }),
      }),
      syntax: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "keyword": "#b083f0", // meta
          "string": "#6fbf73", // ok
          "comment": "#7d8794", // muted
          "number": "#d2a24c", // warn
          "key": "#ff8585", // error
          "type": "#f0883e", // accent
          "function": "#6cb6ff", // info
          "operator": "#56cfcf", // identifier
          "punctuation": "#8b949e", // dim
        }),
        classes: classesOf(DARK, "syntax"),
      }),
      spectrum: lend(DARK, "spectrum"),
    }),
    fourBit: DARK.fourBit,
    composed: Object.freeze({
      "surface.bgElev": Object.freeze({
        "syntax.comment": "#87919e",
        "tone.muted": "#87919e",
      }),
      "surface.focusGround": Object.freeze({
        "syntax.comment": "#919ba8",
        "tone.muted": "#919ba8",
      }),
      "surface.selection": Object.freeze({
        "categorical.c4": "#dec2ed",
        "categorical.c8": "#bfc7d0",
        "syntax.comment": "#bfc7d0",
        "syntax.keyword": "#dec2ed",
        "syntax.punctuation": "#bfc7d0",
        "tone.dim": "#bfc7d0",
        "tone.meta": "#dec2ed",
        "tone.muted": "#bfc7d0",
      }),
    }),
  }),
  "warm": Object.freeze({
    name: "Ember",
    variant: "dark",
    background: "terminal",
    surfaces: Object.freeze({
      "bg": "#1c1917",
      "bgElev": "#252220",
      "bgDeep": "#141211",
      "selection": "#3d2f22",
      "meterFill": "#2f5140",
      "border": "#332e2a",
      "borderStrong": "#443d38",
      "diffAdd": "#1d2a15",
      "diffRemove": "#3a1a18",
      "errorGround": "#b8514a",
      "mAuto": "#6e5423",
      "mAccept": "#523a5c",
      "mPlan": "#2c4a5c",
      "mManual": "#3e3833",
      "skipGround": "#7a2420",
      "focusGround": "#302b28",
      "errorInk": "#fff6f2",
      "mInk": "#f7f2ea",
      "skipInk": "#fff0ec",
      "pick": "#e89f5c",
      "pickInk": "#000000",
      "link": "#77bdb0",
      "linkInk": "#000000",
      "chosen": "#94b872",
      "chosenInk": "#000000",
    }),
    palettes: Object.freeze({
      tone: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "default": "#e0d8d0",
          "dim": "#a09488",
          "muted": "#948a80",
          "ok": "#94b872",
          "warn": "#d9a94e",
          "error": "#ea7f78",
          "info": "#79a9c4",
          "accent": "#e89f5c",
          "meta": "#c194c9",
          "identifier": "#77bdb0",
        }),
        // The 1-bit typographic fallback per slot (C10 I15). The registry carries
        // no such record, and a tone that resolves to nothing at 1-bit carries
        // nothing — so DARK's classes stand, as with the palettes below.
        classes: classesOf(DARK, "tone"),
      }),
      // Derived from this theme's own registry tones — see SYNTAX_FROM_TONE.
      categorical: Object.freeze({
        carries: "decoration",
        monochrome: "foreground",
        slots: Object.freeze({
          "c1": "#79a9c4", // info
          "c2": "#94b872", // ok
          "c3": "#d9a94e", // warn
          "c4": "#c194c9", // meta
          "c5": "#77bdb0", // identifier
          "c6": "#e89f5c", // accent
          "c7": "#ea7f78", // error
          "c8": "#a09488", // dim
        }),
      }),
      syntax: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "keyword": "#c194c9", // meta
          "string": "#94b872", // ok
          "comment": "#948a80", // muted
          "number": "#d9a94e", // warn
          "key": "#ea7f78", // error
          "type": "#e89f5c", // accent
          "function": "#79a9c4", // info
          "operator": "#77bdb0", // identifier
          "punctuation": "#a09488", // dim
        }),
        classes: classesOf(DARK, "syntax"),
      }),
      spectrum: lend(DARK, "spectrum"),
    }),
    fourBit: DARK.fourBit,
    composed: Object.freeze({
      "surface.focusGround": Object.freeze({
        "syntax.comment": "#9e948a",
        "tone.muted": "#9e948a",
      }),
      "surface.selection": Object.freeze({
        "categorical.c8": "#cfc7bf",
        "syntax.comment": "#cfc7bf",
        "syntax.punctuation": "#cfc7bf",
        "tone.dim": "#cfc7bf",
        "tone.muted": "#cfc7bf",
      }),
    }),
  }),
  "nord": Object.freeze({
    name: "Frost",
    variant: "dark",
    background: "terminal",
    surfaces: Object.freeze({
      "bg": "#2e3440",
      "bgElev": "#3b4252",
      "bgDeep": "#272c36",
      "selection": "#3f5570",
      "meterFill": "#4e6544",
      "border": "#434c5e",
      "borderStrong": "#4c566a",
      "diffAdd": "#2f3f33",
      "diffRemove": "#43303a",
      "errorGround": "#bf616a",
      "mAuto": "#6b5b32",
      "mAccept": "#5a4557",
      "mPlan": "#3b5771",
      "mManual": "#434c5e",
      "skipGround": "#7a3238",
      "focusGround": "#485264",
      "errorInk": "#000000",
      "mInk": "#eceff4",
      "skipInk": "#fdf2f4",
      "pick": "#ebae76",
      "pickInk": "#000000",
      "link": "#88c0d0",
      "linkInk": "#000000",
      "chosen": "#a3be8c",
      "chosenInk": "#000000",
    }),
    palettes: Object.freeze({
      tone: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "default": "#d8dee9",
          "dim": "#a6aec0",
          "muted": "#98a0b0",
          "ok": "#a3be8c",
          "warn": "#ebcb8b",
          "error": "#e8967c",
          "info": "#81a1c1",
          "accent": "#ebae76",
          "meta": "#ba96b3",
          "identifier": "#88c0d0",
        }),
        // The 1-bit typographic fallback per slot (C10 I15). The registry carries
        // no such record, and a tone that resolves to nothing at 1-bit carries
        // nothing — so DARK's classes stand, as with the palettes below.
        classes: classesOf(DARK, "tone"),
      }),
      // Derived from this theme's own registry tones — see SYNTAX_FROM_TONE.
      categorical: Object.freeze({
        carries: "decoration",
        monochrome: "foreground",
        slots: Object.freeze({
          "c1": "#81a1c1", // info
          "c2": "#a3be8c", // ok
          "c3": "#ebcb8b", // warn
          "c4": "#ba96b3", // meta
          "c5": "#88c0d0", // identifier
          "c6": "#ebae76", // accent
          "c7": "#e8967c", // error
          "c8": "#a6aec0", // dim
        }),
      }),
      syntax: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "keyword": "#ba96b3", // meta
          "string": "#a3be8c", // ok
          "comment": "#98a0b0", // muted
          "number": "#ebcb8b", // warn
          "key": "#e8967c", // error
          "type": "#ebae76", // accent
          "function": "#81a1c1", // info
          "operator": "#88c0d0", // identifier
          "punctuation": "#a6aec0", // dim
        }),
        classes: classesOf(DARK, "syntax"),
      }),
      spectrum: lend(DARK, "spectrum"),
    }),
    fourBit: DARK.fourBit,
    composed: Object.freeze({
      "surface.bgElev": Object.freeze({
        "categorical.c1": "#95b5d5",
        "categorical.c4": "#c8a2c1",
        "categorical.c7": "#f2a086",
        "syntax.comment": "#acb4c4",
        "syntax.function": "#95b5d5",
        "syntax.key": "#f2a086",
        "syntax.keyword": "#c8a2c1",
        "tone.error": "#f2a086",
        "tone.info": "#95b5d5",
        "tone.meta": "#c8a2c1",
        "tone.muted": "#acb4c4",
      }),
      "surface.diffAdd": Object.freeze({
        "syntax.function": "#88a8c8",
        "syntax.keyword": "#be9ab7",
      }),
      "surface.focusGround": Object.freeze({
        "categorical.c1": "#a9c9e9",
        "categorical.c2": "#b7d2a0",
        "categorical.c4": "#e6c0df",
        "categorical.c5": "#9cd4e4",
        "categorical.c6": "#f5b880",
        "categorical.c7": "#ffb49a",
        "categorical.c8": "#c4ccde",
        "syntax.comment": "#c0c8d8",
        "syntax.function": "#a9c9e9",
        "syntax.key": "#ffb49a",
        "syntax.keyword": "#e6c0df",
        "syntax.operator": "#9cd4e4",
        "syntax.punctuation": "#c4ccde",
        "syntax.string": "#b7d2a0",
        "syntax.type": "#f5b880",
        "tone.accent": "#f5b880",
        "tone.dim": "#c4ccde",
        "tone.error": "#ffb49a",
        "tone.identifier": "#9cd4e4",
        "tone.info": "#a9c9e9",
        "tone.meta": "#e6c0df",
        "tone.muted": "#c0c8d8",
        "tone.ok": "#b7d2a0",
      }),
      "surface.selection": Object.freeze({
        "categorical.c1": "#c4e1ff",
        "categorical.c2": "#c7e6b0",
        "categorical.c4": "#f1c9e7",
        "categorical.c5": "#bfeaf4",
        "categorical.c6": "#ffd0a8",
        "categorical.c7": "#ffcab8",
        "categorical.c8": "#d8dee9",
        "syntax.comment": "#d8dee9",
        "syntax.function": "#c4e1ff",
        "syntax.key": "#ffcab8",
        "syntax.keyword": "#f1c9e7",
        "syntax.operator": "#bfeaf4",
        "syntax.punctuation": "#d8dee9",
        "syntax.string": "#c7e6b0",
        "syntax.type": "#ffd0a8",
        "tone.accent": "#ffd0a8",
        "tone.dim": "#d8dee9",
        "tone.error": "#ffcab8",
        "tone.identifier": "#bfeaf4",
        "tone.info": "#c4e1ff",
        "tone.meta": "#f1c9e7",
        "tone.muted": "#d8dee9",
        "tone.ok": "#c7e6b0",
      }),
    }),
  }),
  "viol": Object.freeze({
    name: "Iris",
    variant: "dark",
    background: "terminal",
    surfaces: Object.freeze({
      "bg": "#1a1725",
      "bgElev": "#231f31",
      "bgDeep": "#13111b",
      "selection": "#33285c",
      "meterFill": "#3d6047",
      "border": "#312c42",
      "borderStrong": "#443c5a",
      "diffAdd": "#16301f",
      "diffRemove": "#3a1626",
      "errorGround": "#c05a72",
      "mAuto": "#63512a",
      "mAccept": "#4a3470",
      "mPlan": "#2a4570",
      "mManual": "#3a3450",
      "skipGround": "#6e1a34",
      "focusGround": "#292339",
      "errorInk": "#000000",
      "mInk": "#f4f0ff",
      "skipInk": "#ffeef4",
      "pick": "#c79bf0",
      "pickInk": "#000000",
      "link": "#7fd4d4",
      "linkInk": "#000000",
      "chosen": "#8fd1a0",
      "chosenInk": "#000000",
    }),
    palettes: Object.freeze({
      tone: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "default": "#ddd6f3",
          "dim": "#9d95b8",
          "muted": "#8f88a8",
          "ok": "#8fd1a0",
          "warn": "#e0c07a",
          "error": "#f08fa0",
          "info": "#8fb8e8",
          "accent": "#c79bf0",
          "meta": "#e89bd0",
          "identifier": "#7fd4d4",
        }),
        // The 1-bit typographic fallback per slot (C10 I15). The registry carries
        // no such record, and a tone that resolves to nothing at 1-bit carries
        // nothing — so DARK's classes stand, as with the palettes below.
        classes: classesOf(DARK, "tone"),
      }),
      // Derived from this theme's own registry tones — see SYNTAX_FROM_TONE.
      categorical: Object.freeze({
        carries: "decoration",
        monochrome: "foreground",
        slots: Object.freeze({
          "c1": "#8fb8e8", // info
          "c2": "#8fd1a0", // ok
          "c3": "#e0c07a", // warn
          "c4": "#e89bd0", // meta
          "c5": "#7fd4d4", // identifier
          "c6": "#c79bf0", // accent
          "c7": "#f08fa0", // error
          "c8": "#9d95b8", // dim
        }),
      }),
      syntax: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "keyword": "#e89bd0", // meta
          "string": "#8fd1a0", // ok
          "comment": "#8f88a8", // muted
          "number": "#e0c07a", // warn
          "key": "#f08fa0", // error
          "type": "#c79bf0", // accent
          "function": "#8fb8e8", // info
          "operator": "#7fd4d4", // identifier
          "punctuation": "#9d95b8", // dim
        }),
        classes: classesOf(DARK, "syntax"),
      }),
      spectrum: lend(DARK, "spectrum"),
    }),
    fourBit: DARK.fourBit,
    composed: Object.freeze({
      "surface.focusGround": Object.freeze({
        "syntax.comment": "#9992b2",
        "tone.muted": "#9992b2",
      }),
      "surface.selection": Object.freeze({
        "syntax.comment": "#c8c0dd",
        "tone.muted": "#c8c0dd",
      }),
    }),
  }),
  "mono": Object.freeze({
    name: "Mono",
    variant: "dark",
    background: "terminal",
    surfaces: Object.freeze({
      "bg": "#161616",
      "bgElev": "#1e1e1e",
      "bgDeep": "#111111",
      "selection": "#333333",
      "meterFill": "#555555",
      "border": "#2a2a2a",
      "borderStrong": "#3a3a3a",
      "diffAdd": "#1f1f1f",
      "diffRemove": "#2b2b2b",
      "errorGround": "#e0e0e0",
      "mAuto": "#4a4a4a",
      "mAccept": "#3a3a3a",
      "mPlan": "#2e2e2e",
      "mManual": "#242424",
      "skipGround": "#5a5a5a",
      "focusGround": "#2a2a2a",
      "errorInk": "#161616",
      "mInk": "#f0f0f0",
      "skipInk": "#ffffff",
      "pick": "#ffffff",
      "pickInk": "#000000",
      "link": "#c4c4c4",
      "linkInk": "#000000",
      "chosen": "#b8b8b8",
      "chosenInk": "#000000",
    }),
    palettes: Object.freeze({
      tone: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "default": "#e0e0e0",
          "dim": "#9a9a9a",
          "muted": "#8a8a8a",
          "ok": "#b8b8b8",
          "warn": "#d0d0d0",
          "error": "#ffffff",
          "info": "#a8a8a8",
          "accent": "#f0f0f0",
          "meta": "#8e8e8e",
          "identifier": "#c4c4c4",
        }),
        // The 1-bit typographic fallback per slot (C10 I15). The registry carries
        // no such record, and a tone that resolves to nothing at 1-bit carries
        // nothing — so DARK's classes stand, as with the palettes below.
        classes: classesOf(DARK, "tone"),
      }),
      // Derived from this theme's own registry tones — see SYNTAX_FROM_TONE.
      categorical: Object.freeze({
        carries: "decoration",
        monochrome: "foreground",
        slots: Object.freeze({
          "c1": "#a8a8a8", // info
          "c2": "#b8b8b8", // ok
          "c3": "#d0d0d0", // warn
          "c4": "#8e8e8e", // meta
          "c5": "#c4c4c4", // identifier
          "c6": "#f0f0f0", // accent
          "c7": "#ffffff", // error
          "c8": "#9a9a9a", // dim
        }),
      }),
      syntax: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "keyword": "#8e8e8e", // meta
          "string": "#b8b8b8", // ok
          "comment": "#8a8a8a", // muted
          "number": "#d0d0d0", // warn
          "key": "#ffffff", // error
          "type": "#f0f0f0", // accent
          "function": "#a8a8a8", // info
          "operator": "#c4c4c4", // identifier
          "punctuation": "#9a9a9a", // dim
        }),
        classes: classesOf(DARK, "syntax"),
      }),
      spectrum: lend(DARK, "spectrum"),
    }),
    fourBit: DARK.fourBit,
    composed: Object.freeze({
      "surface.diffRemove": Object.freeze({
        "syntax.keyword": "#929292",
      }),
      "surface.focusGround": Object.freeze({
        "categorical.c4": "#989898",
        "syntax.comment": "#949494",
        "syntax.keyword": "#989898",
        "tone.meta": "#989898",
        "tone.muted": "#949494",
      }),
      "surface.selection": Object.freeze({
        "categorical.c4": "#b8b8b8",
        "categorical.c8": "#b8b8b8",
        "syntax.comment": "#b8b8b8",
        "syntax.keyword": "#b8b8b8",
        "syntax.punctuation": "#b8b8b8",
        "tone.dim": "#b8b8b8",
        "tone.meta": "#b8b8b8",
        "tone.muted": "#b8b8b8",
      }),
    }),
  }),
  "paper": Object.freeze({
    name: "Paper",
    variant: "light",
    background: "surface",
    surfaces: Object.freeze({
      "bg": "#f7f4ee",
      "bgElev": "#efeae1",
      "bgDeep": "#e6e0d5",
      "selection": "#d6e4f0",
      "meterFill": "#cddfc3",
      "border": "#d8d0c2",
      "borderStrong": "#c4baa8",
      "diffAdd": "#dff0dc",
      "diffRemove": "#fae3de",
      "errorGround": "#a52f22",
      "mAuto": "#f0e0b4",
      "mAccept": "#ecd9ef",
      "mPlan": "#d4e6f2",
      "mManual": "#ddd6c8",
      "skipGround": "#8c231a",
      "focusGround": "#e4ddd0",
      "errorInk": "#fff8f4",
      "mInk": "#2e2a24",
      "skipInk": "#fff4f0",
      "pick": "#1a56c4",
      "pickInk": "#ffffff",
      "link": "#0a6b7a",
      "linkInk": "#ffffff",
      "chosen": "#3f7040",
      "chosenInk": "#ffffff",
    }),
    palettes: Object.freeze({
      tone: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "default": "#3a3530",
          "dim": "#6b625a",
          "muted": "#6f675d",
          "ok": "#3f7040",
          "warn": "#8a6008",
          "error": "#b3301f",
          "info": "#1f6b94",
          "accent": "#1a56c4",
          "meta": "#8d3f8f",
          "identifier": "#0a6b7a",
        }),
        // The 1-bit typographic fallback per slot (C10 I15). The registry carries
        // no such record, and a tone that resolves to nothing at 1-bit carries
        // nothing — so LIGHT's classes stand, as with the palettes below.
        classes: classesOf(LIGHT, "tone"),
      }),
      // Derived from this theme's own registry tones — see SYNTAX_FROM_TONE.
      categorical: Object.freeze({
        carries: "decoration",
        monochrome: "foreground",
        slots: Object.freeze({
          "c1": "#1f6b94", // info
          "c2": "#3f7040", // ok
          "c3": "#8a6008", // warn
          "c4": "#8d3f8f", // meta
          "c5": "#0a6b7a", // identifier
          "c6": "#1a56c4", // accent
          "c7": "#b3301f", // error
          "c8": "#6b625a", // dim
        }),
      }),
      syntax: Object.freeze({
        carries: "meaning",
        monochrome: "typographic",
        slots: Object.freeze({
          "keyword": "#8d3f8f", // meta
          "string": "#3f7040", // ok
          "comment": "#6f675d", // muted
          "number": "#8a6008", // warn
          "key": "#b3301f", // error
          "type": "#1a56c4", // accent
          "function": "#1f6b94", // info
          "operator": "#0a6b7a", // identifier
          "punctuation": "#6b625a", // dim
        }),
        classes: classesOf(LIGHT, "syntax"),
      }),
      spectrum: lend(LIGHT, "spectrum"),
    }),
    fourBit: LIGHT.fourBit,
    composed: Object.freeze({
      "surface.bgDeep": Object.freeze({
        "categorical.c1": "#15618a",
        "categorical.c2": "#356636",
        "categorical.c3": "#805600",
        "syntax.comment": "#655d53",
        "syntax.function": "#15618a",
        "syntax.number": "#805600",
        "syntax.string": "#356636",
        "tone.info": "#15618a",
        "tone.muted": "#655d53",
        "tone.ok": "#356636",
        "tone.warn": "#805600",
      }),
      "surface.focusGround": Object.freeze({
        "categorical.c1": "#15618a",
        "categorical.c2": "#356636",
        "categorical.c3": "#805600",
        "categorical.c8": "#615850",
        "syntax.comment": "#655d53",
        "syntax.function": "#15618a",
        "syntax.number": "#805600",
        "syntax.punctuation": "#615850",
        "syntax.string": "#356636",
        "tone.dim": "#615850",
        "tone.info": "#15618a",
        "tone.muted": "#655d53",
        "tone.ok": "#356636",
        "tone.warn": "#805600",
      }),
      "surface.selection": Object.freeze({
        "categorical.c3": "#704800",
        "syntax.comment": "#5d554c",
        "syntax.number": "#704800",
        "tone.muted": "#5d554c",
        "tone.warn": "#704800",
      }),
    }),
  }),
});
