// The curated tables, and the list of them — one declaration read by the row
// that pins them (C10 T2.39) and by the tool that re-takes the pin
// (`tools/curated/pin.ts`). Two copies of this list would be the drift the pin
// exists to prevent, one level out.
//
// **Why the values are pinned in a file rather than as digests in the row.** A
// digest is total — any different value fails, which is what *legal-but-
// different must fail* means — and it is opaque, so a failure says *something
// moved* and nothing about what. A table change that is legitimate then has to
// be reviewed by reading two revisions of the module side by side.
//
// Pinning the canonical **values** in `curated-pinned.json` is total in exactly
// the same way and reviewable as well: a deliberate change shows up as a diff of
// the entries, and a failing row prints the entries that moved rather than a new
// hash. The cost is a data file; the alternative was a hash plus a second copy
// of the values to diff against, which is the same file with a hash on top.
//
// **It is not a snapshot.** There is no `-u` and no write path from the test —
// re-taking the pin is `npx tsx tools/curated/pin.ts --write`, a deliberate act
// with a diff to read afterwards. A snapshot regenerated by a flag records what
// the code does; this records what was chosen.
import { createHash } from "node:crypto";
import {
  DARK_FOUR_BIT,
  HIGH_CONTRAST_FOUR_BIT,
  LIGHT_FOUR_BIT,
  MUST_STAY_DISTINCT,
} from "../../src/presentation/theme/four-bit.js";
import { OKABE_ITO_CANONICAL, VISIONS } from "../../src/presentation/theme/cvd.js";
import { COLORMAPS } from "../../src/presentation/theme/colormap.js";
import { CATEGORY_REFS } from "../../src/presentation/theme/categorical.js";
import { REQUIRED_SLOTS } from "../../src/presentation/theme/contrast.js";
import {
  GLYPH_SUBSTITUTIONS,
  GLYPH_TOKENS,
  SPINNER_SETS,
  SUBSTITUTIONS,
  barStyle,
  barStyleNames,
  glyphs,
} from "../../src/presentation/blocks/glyphs.js";

const FULL = { unicode: "full", ambiguousWidth: "narrow" } as const;

/**
 * **Key order is not part of a table's identity, and its values are.** The
 * canonical form sorts a record's keys and keeps an array's order, so
 * re-ordering declarations is free and changing one index is not — which is the
 * line this pin wants, since a curated map's order is how it reads and its
 * values are what it promises.
 */
export const canon = (v: unknown): unknown => {
  if (Array.isArray(v)) return v.map(canon);
  if (v !== null && typeof v === "object") {
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(v as object).sort()) out[k] = canon((v as Record<string, unknown>)[k]);
    return out;
  }
  return v;
};

/**
 * Every hand-chosen table, by the name it is pinned under.
 *
 * `GLYPH_TABLE` and `BAR_STYLES` are module-private, so they are pinned through
 * the projections that ship — which is the better subject anyway: what a caller
 * receives, rather than the literal behind it.
 */
export const CURATED: Readonly<Record<string, unknown>> = {
  // C10 §2 — the three 4-bit maps. Sixteen indices whose *values* are the
  // emulator's, so what is curated is which slot takes which index.
  DARK_FOUR_BIT,
  LIGHT_FOUR_BIT,
  HIGH_CONTRAST_FOUR_BIT,
  MUST_STAY_DISTINCT,

  // C10 §4j — the calibrating set. A *different* palette that also separates
  // under all three dichromacies would pass `collisions() === []` exactly as
  // this one does, which is why the control is pinned and not merely checked.
  OKABE_ITO_CANONICAL,
  VISIONS,

  // C10 §4h, §4j — the colormaps and the categorical refs.
  COLORMAPS,
  CATEGORY_REFS,
  REQUIRED_SLOTS,

  // C09 §4 — the alphabets. A spinner frame swapped for another one-cell glyph,
  // or an ASCII fallback swapped for another ASCII character, passes every width
  // and distinctness row this repository has.
  SPINNER_SETS,
  SUBSTITUTIONS,
  GLYPH_SUBSTITUTIONS,
  GLYPH_TOKENS,

  "glyphs(full)": glyphs(FULL),
  "glyphs(ascii)": glyphs({ ...FULL, unicode: "ascii" }),
  // **A bar alphabet is capability-dependent, so it is pinned at both rungs.**
  // The first draft of this pin read `barStyle(name)` — `barStyle` takes the
  // capabilities first, so every one of the nine entries resolved to the same
  // default style and the pin held nine copies of one value. It was a digest, so
  // it looked exactly like a pin; `tsc` is what found it, which is the argument
  // for type-checking a test file and not only running it.
  "barStyles(full)": Object.fromEntries(barStyleNames().map((n) => [n, barStyle(FULL, n)])),
  //
  // The ASCII rung collapses all nine alphabets onto one pair, which is the
  // design's own answer and not this defect repeating: there is one ASCII bar,
  // so the nine names all resolve to it. Pinned so that collapse is recorded
  // rather than rediscovered.
  "barStyles(ascii)": Object.fromEntries(
    barStyleNames().map((n) => [n, barStyle({ ...FULL, unicode: "ascii" }, n)]),
  ),
};

/**
 * Exported frozen tables in the curated modules that are **derived** and need no
 * pin — each with the reason, because *derived* is a claim and an unstated one
 * reads as an omission.
 */
export const DERIVED: Readonly<Record<string, string>> = {
  CUBE_LEVELS: "the xterm 256-colour cube's own six levels — the emulator's, not a choice",
  NO_STYLE: "the empty Style; its emptiness is the claim and C09 T1.2 asserts it",
  MARKER3_COLUMN: "C12's 3-D marker column, derived from the braille block's own encoding",
  DARK: "the ink oracle's frozen palette — `test/support/ink-oracle.ts` pins it at 1 913 captures",
  LIGHT: "a lender for the 4-bit rung; the shipped light theme is the registry's",
  HIGH_CONTRAST: "the same, and T2.39a pins its 4-bit map by reference",
};

/** The modules the driver scans, so a table added to one of them cannot go unpinned. */
export const MODULES: readonly string[] = [
  "src/presentation/theme/four-bit.ts",
  "src/presentation/theme/cvd.ts",
  "src/presentation/theme/colormap.ts",
  "src/presentation/theme/categorical.ts",
  "src/presentation/theme/contrast.ts",
  "src/presentation/theme/types.ts",
  "src/presentation/theme/index.ts",
  "src/presentation/theme/tokens-dark.ts",
  "src/presentation/theme/tokens-light.ts",
  "src/presentation/theme/tokens-high-contrast.ts",
  "src/presentation/blocks/glyphs.ts",
];

/**
 * The one table whose *bulk* is reduced before pinning, with the reason — an
 * unstated reduction is a pin with a hole in it.
 *
 * `COLORMAPS` is 142 maps of 256 transcribed triples, and pinning every sample
 * by value is a 1.5 MB file for a table whose samples are **matplotlib's**, not
 * a choice made here. What *is* curated is which 142 maps ship, each one's
 * `kind`, and the reversed pairs — so those are pinned by value and the sample
 * array by a digest, which still names the map that moved. Every other table is
 * pinned whole.
 */
const REDUCE: Readonly<Record<string, (v: unknown) => unknown>> = {
  COLORMAPS: (v) => {
    const out: Record<string, unknown> = {};
    for (const [name, map] of Object.entries(v as Record<string, Record<string, unknown>>)) {
      out[name] = {
        kind: map["kind"],
        name: map["name"],
        data: `sha256:${createHash("sha256").update(JSON.stringify(map["data"])).digest("hex").slice(0, 16)}`,
      };
    }
    return out;
  },
};

/** The canonical form of every curated table, which is what `curated-pinned.json` holds. */
export const canonical = (): Record<string, unknown> => {
  const out: Record<string, unknown> = {};
  for (const name of Object.keys(CURATED).sort()) {
    const reduce = REDUCE[name];
    out[name] = canon(reduce === undefined ? CURATED[name] : reduce(CURATED[name]));
  }
  return out;
};

/**
 * The entries that differ between two canonical tables, as `path: was → now`.
 *
 * **This is the part the digest could not do.** A failing pin prints these, so a
 * legitimate change is read as a list of entries rather than as a hash nobody
 * can interpret — and an illegitimate one names the slot it touched.
 */
/**
 * A value short enough to read in a failure.
 *
 * **Measured rather than guessed at**: the first run of the differ printed 142
 * colormaps' full sample arrays — 456 KB of output for a change a reader wanted
 * one line about. A pin that cannot be read at the moment it fails is a digest
 * with extra steps.
 */
const show = (v: unknown): string => {
  if (v === undefined) return "(absent)";
  const text = JSON.stringify(v);
  return text.length <= 120 ? text : `${text.slice(0, 117)}…`;
};

export const entryDiff = (was: unknown, now: unknown, path = ""): readonly string[] => {
  const at = (k: string): string => (path === "" ? k : `${path}.${k}`);
  if (Array.isArray(was) && Array.isArray(now)) {
    const out: string[] = [];
    for (let i = 0; i < Math.max(was.length, now.length); i += 1) {
      out.push(...entryDiff(was[i], now[i], at(String(i))));
    }
    return out;
  }
  if (was !== null && now !== null && typeof was === "object" && typeof now === "object") {
    const keys = [...new Set([...Object.keys(was), ...Object.keys(now)])].sort();
    const out: string[] = [];
    for (const k of keys) {
      out.push(...entryDiff((was as Record<string, unknown>)[k], (now as Record<string, unknown>)[k], at(k)));
    }
    return out;
  }
  if (JSON.stringify(was) === JSON.stringify(now)) return [];
  return [`${path === "" ? "(the whole value)" : path}: ${show(was)} → ${show(now)}`];
};
