// C10 I68 — the quantised shortfalls, recorded when I68 landed and held by
// equality in T2.74 and T2.75. Each entry is `<ground>.<palette>.<slot>` (or
// `hueBand.<name>`) and the ratio to two places.
//
// **The two lists mean different things.** At 8 bits the cube's RGB is fixed,
// so every entry is a defect, owed, and this list is expected to end empty — a
// remedy removes its lines here and nothing else may. At 4 bits the ratios are
// against the reference palette (`ANSI16_HEX`), because a terminal's low
// sixteen are the user's, so the list is an exemption list in T2.64's shape.
//
// **Not generated, on purpose**: a list written by the function it checks
// agrees with it by construction. It was read out once, when the row landed,
// and checked against an independent probe that found the same 193 and 403
// cells; it changes only by an edit someone reads.

/** At 8 bits, per theme — 193 entries. */
export const EIGHT_BIT_SHORTFALLS: Readonly<Record<string, readonly string[]>> = {
  dark: [
    "bgElev.syntax.comment 2.88",
    "bgElev.syntax.key 4.10",
    "focusGround.tone.error 4.43",
    "focusGround.syntax.keyword 3.42",
    "focusGround.syntax.comment 2.91",
    "focusGround.syntax.number 4.06",
    "focusGround.syntax.key 3.58",
    "diffRemove.syntax.keyword 4.38",
    "diffRemove.syntax.comment 2.69",
    "diffRemove.syntax.key 3.83",
    "bg.categorical.c6 4.48",
    "bgElev.categorical.c6 3.98",
    "focusGround.categorical.c6 3.47",
    "hueBand.purple 3.56",
  ],
  light: [
    "bg.tone.ok 4.10",
    "bg.tone.identifier 4.13",
    "bg.syntax.string 4.10",
    "bg.syntax.operator 4.13",
    "bgElev.tone.ok 3.54",
    "bgElev.tone.info 3.56",
    "bgElev.tone.accent 4.44",
    "bgElev.tone.identifier 3.56",
    "bgElev.syntax.string 3.54",
    "bgElev.syntax.function 4.44",
    "bgElev.syntax.operator 3.56",
    "focusGround.tone.warn 4.10",
    "focusGround.tone.accent 3.68",
    "focusGround.syntax.string 2.94",
    "focusGround.syntax.comment 2.57",
    "focusGround.syntax.number 4.10",
    "focusGround.syntax.key 2.64",
    "focusGround.syntax.type 4.10",
    "focusGround.syntax.function 3.66",
    "focusGround.syntax.operator 2.95",
    "diffAdd.syntax.string 3.75",
    "diffAdd.syntax.operator 3.77",
    "diffAdd.tone.ok 3.75",
    "diffRemove.syntax.string 3.54",
    "diffRemove.syntax.function 4.44",
    "diffRemove.syntax.operator 3.56",
    "diffRemove.tone.ok 3.54",
    "bg.categorical.c1 3.34",
    "bg.categorical.c2 4.13",
    "bg.categorical.c4 3.82",
    "bg.categorical.c7 4.37",
    "bgElev.categorical.c1 2.88",
    "bgElev.categorical.c2 3.56",
    "bgElev.categorical.c3 3.91",
    "bgElev.categorical.c4 3.29",
    "bgElev.categorical.c6 4.06",
    "bgElev.categorical.c7 3.76",
    "focusGround.categorical.c1 4.10",
  ],
  hcDark: [
    "bg.tone.warn 6.29",
    "bg.syntax.keyword 6.97",
    "bg.syntax.type 6.29",
    "bgElev.tone.muted 6.99",
    "bgElev.tone.ok 6.36",
    "bgElev.tone.warn 5.61",
    "bgElev.tone.error 6.29",
    "bgElev.tone.accent 6.90",
    "bgElev.tone.identifier 6.91",
    "bgElev.syntax.keyword 6.22",
    "bgElev.syntax.string 6.36",
    "bgElev.syntax.comment 6.99",
    "bgElev.syntax.key 6.46",
    "bgElev.syntax.type 5.61",
    "bgElev.syntax.operator 6.91",
    "focusGround.tone.default 6.45",
    "focusGround.tone.dim 6.45",
    "focusGround.tone.muted 6.45",
    "focusGround.tone.ok 6.45",
    "focusGround.tone.warn 6.45",
    "focusGround.tone.error 6.45",
    "focusGround.tone.info 6.45",
    "focusGround.tone.accent 6.45",
    "focusGround.tone.meta 6.45",
    "focusGround.tone.identifier 6.45",
    "focusGround.syntax.keyword 6.45",
    "focusGround.syntax.string 6.45",
    "focusGround.syntax.comment 6.45",
    "focusGround.syntax.number 6.45",
    "focusGround.syntax.key 6.45",
    "focusGround.syntax.type 6.45",
    "focusGround.syntax.function 6.45",
    "focusGround.syntax.operator 6.45",
    "focusGround.syntax.punctuation 6.45",
    "diffAdd.syntax.keyword 4.86",
    "diffAdd.syntax.string 4.07",
    "diffAdd.syntax.comment 4.19",
    "diffAdd.syntax.number 4.32",
    "diffAdd.syntax.key 4.69",
    "diffAdd.syntax.type 3.80",
    "diffAdd.syntax.function 5.00",
    "diffAdd.syntax.operator 4.62",
    "diffAdd.syntax.punctuation 5.53",
    "diffAdd.tone.ok 4.13",
    "diffAdd.tone.error 4.55",
    "diffAdd.tone.muted 4.19",
    "diffRemove.syntax.keyword 6.84",
    "diffRemove.syntax.string 4.80",
    "diffRemove.syntax.comment 5.94",
    "diffRemove.syntax.number 5.86",
    "diffRemove.syntax.key 6.28",
    "diffRemove.syntax.type 6.74",
    "diffRemove.syntax.function 6.10",
    "diffRemove.syntax.operator 5.21",
    "diffRemove.tone.error 6.10",
    "diffRemove.tone.muted 5.94",
    "hueBand.blue 3.55",
    "hueBand.purple 3.56",
  ],
  hcLight: [
    "diffAdd.syntax.number 5.23",
    "diffAdd.syntax.key 6.79",
    "diffAdd.syntax.function 5.89",
    "diffAdd.syntax.operator 6.84",
    "diffAdd.tone.error 6.79",
    "diffRemove.syntax.string 6.05",
    "diffRemove.syntax.number 4.35",
    "diffRemove.syntax.function 4.90",
    "diffRemove.syntax.operator 5.69",
    "diffRemove.tone.ok 6.05",
    "bgDeep.tone.meta 6.84",
  ],
  ink: [
    "hueBand.purple 3.56",
  ],
  warm: [
    "bg.syntax.punctuation 4.32",
    "bgElev.tone.error 4.10",
    "bgElev.syntax.key 4.10",
    "bgElev.syntax.punctuation 3.83",
    "diffAdd.syntax.key 4.10",
    "diffAdd.syntax.punctuation 3.83",
    "diffAdd.tone.error 4.10",
    "diffRemove.syntax.key 4.10",
    "diffRemove.syntax.punctuation 3.83",
    "diffRemove.tone.error 4.10",
    "bg.categorical.c8 4.32",
    "bgElev.categorical.c7 4.10",
    "bgElev.categorical.c8 3.83",
    "focusGround.categorical.c7 4.10",
    "focusGround.categorical.c8 3.83",
    "hueBand.purple 3.56",
  ],
  nord: [
    "bg.tone.info 4.01",
    "bg.syntax.function 4.01",
    "bgElev.tone.info 4.24",
    "bgElev.tone.meta 3.20",
    "bgElev.syntax.keyword 3.20",
    "bgElev.syntax.function 4.24",
    "bgElev.syntax.punctuation 4.10",
    "focusGround.tone.info 3.62",
    "focusGround.syntax.function 3.62",
    "diffRemove.syntax.function 4.01",
    "bg.categorical.c1 4.01",
    "bgElev.categorical.c1 4.24",
    "bgElev.categorical.c4 3.20",
    "bgElev.categorical.c8 4.10",
    "focusGround.categorical.c1 3.62",
  ],
  viol: [
    "bgElev.syntax.punctuation 4.41",
    "focusGround.syntax.punctuation 4.41",
    "diffAdd.syntax.punctuation 4.41",
    "diffRemove.syntax.punctuation 4.41",
    "bgElev.categorical.c8 4.41",
    "focusGround.categorical.c8 4.41",
    "hueBand.purple 3.56",
  ],
  mono: [
    "diffRemove.syntax.keyword 4.35",
    "hueBand.purple 3.56",
  ],
  paper: [
    "bg.tone.ok 3.54",
    "bg.tone.info 3.56",
    "bg.syntax.string 3.54",
    "bg.syntax.function 3.56",
    "bgElev.tone.ok 3.54",
    "bgElev.tone.info 3.56",
    "bgElev.syntax.string 3.54",
    "bgElev.syntax.function 3.56",
    "focusGround.tone.ok 2.94",
    "focusGround.tone.warn 4.10",
    "focusGround.tone.accent 4.15",
    "focusGround.tone.meta 2.96",
    "focusGround.syntax.keyword 2.96",
    "focusGround.syntax.string 2.94",
    "focusGround.syntax.number 4.10",
    "focusGround.syntax.type 4.15",
    "diffAdd.syntax.string 3.54",
    "diffAdd.syntax.function 3.56",
    "diffAdd.tone.ok 3.54",
    "diffRemove.syntax.string 3.23",
    "diffRemove.syntax.function 3.25",
    "diffRemove.tone.ok 3.23",
    "bgDeep.tone.meta 3.25",
    "bg.categorical.c1 3.56",
    "bg.categorical.c2 3.54",
    "bgElev.categorical.c1 3.56",
    "bgElev.categorical.c2 3.54",
    "focusGround.categorical.c2 2.94",
    "focusGround.categorical.c3 4.10",
    "focusGround.categorical.c4 2.96",
    "focusGround.categorical.c6 4.15",
  ],
};

/** dark, ink, warm, nord, viol, mono. */
const FOUR_DARK: readonly string[] = [
  "bg.tone.identifier 4.40",
  "bg.syntax.function 2.44",
  "bgElev.tone.identifier 4.40",
  "bgElev.syntax.function 2.44",
  "focusGround.tone.identifier 4.40",
  "focusGround.syntax.function 2.44",
  "diffAdd.syntax.keyword 1.64",
  "diffAdd.syntax.string 3.74",
  "diffAdd.syntax.comment 1.30",
  "diffAdd.syntax.number 1.22",
  "diffAdd.syntax.key 1.28",
  "diffAdd.syntax.function 1.67",
  "diffAdd.syntax.operator 4.10",
  "diffAdd.syntax.punctuation 2.82",
  "diffAdd.tone.ok 3.74",
  "diffAdd.tone.error 1.28",
  "diffAdd.tone.muted 1.30",
  "diffRemove.syntax.keyword 3.49",
  "diffRemove.syntax.comment 2.77",
  "diffRemove.syntax.number 2.61",
  "diffRemove.syntax.key 2.74",
  "diffRemove.syntax.function 1.27",
  "diffRemove.tone.error 2.74",
  "bg.categorical.c2 4.40",
  "bg.categorical.c3 4.09",
  "bg.categorical.c5 2.44",
  "bg.categorical.c6 1.92",
  "bg.categorical.c7 2.23",
  "bgElev.categorical.c2 4.40",
  "bgElev.categorical.c3 4.09",
  "bgElev.categorical.c5 2.44",
  "bgElev.categorical.c6 1.92",
  "bgElev.categorical.c7 2.23",
  "focusGround.categorical.c2 4.40",
  "focusGround.categorical.c3 4.09",
  "focusGround.categorical.c5 2.44",
  "focusGround.categorical.c6 1.92",
  "focusGround.categorical.c7 2.23",
];

/** light, paper. */
const FOUR_LIGHT: readonly string[] = [
  "bg.tone.warn 4.20",
  "bg.syntax.number 4.20",
  "bg.syntax.type 4.20",
  "bgElev.tone.warn 4.20",
  "bgElev.syntax.number 4.20",
  "bgElev.syntax.type 4.20",
  "focusGround.tone.warn 4.20",
  "focusGround.syntax.number 4.20",
  "focusGround.syntax.type 4.20",
  "diffAdd.syntax.keyword 1.83",
  "diffAdd.syntax.string 1.00",
  "diffAdd.syntax.comment 1.30",
  "diffAdd.syntax.number 1.22",
  "diffAdd.syntax.key 2.13",
  "diffAdd.syntax.type 1.22",
  "diffAdd.syntax.function 3.12",
  "diffAdd.syntax.operator 1.08",
  "diffAdd.syntax.punctuation 4.09",
  "diffAdd.tone.ok 1.00",
  "diffAdd.tone.error 2.13",
  "diffAdd.tone.muted 1.30",
  "diffRemove.syntax.keyword 1.16",
  "diffRemove.syntax.string 2.13",
  "diffRemove.syntax.comment 2.77",
  "diffRemove.syntax.number 2.61",
  "diffRemove.syntax.key 1.00",
  "diffRemove.syntax.type 2.61",
  "diffRemove.syntax.function 1.46",
  "diffRemove.syntax.operator 2.29",
  "diffRemove.syntax.punctuation 1.92",
  "diffRemove.tone.ok 2.13",
  "diffRemove.tone.error 1.00",
  "bg.categorical.c1 4.20",
  "bg.categorical.c7 3.14",
  "bg.categorical.c8 3.95",
  "bgElev.categorical.c1 4.20",
  "bgElev.categorical.c7 3.14",
  "bgElev.categorical.c8 3.95",
  "focusGround.categorical.c1 4.20",
  "focusGround.categorical.c7 3.14",
  "focusGround.categorical.c8 3.95",
];

/** hcDark. */
const FOUR_HCDARK: readonly string[] = [
  "bg.tone.muted 5.32",
  "bg.tone.error 5.25",
  "bg.tone.accent 6.70",
  "bg.tone.meta 2.23",
  "bg.tone.identifier 4.40",
  "bg.syntax.keyword 6.70",
  "bg.syntax.comment 5.32",
  "bg.syntax.key 5.25",
  "bg.syntax.type 5.01",
  "bg.syntax.function 2.44",
  "bgElev.tone.muted 5.32",
  "bgElev.tone.error 5.25",
  "bgElev.tone.accent 6.70",
  "bgElev.tone.meta 2.23",
  "bgElev.tone.identifier 4.40",
  "bgElev.syntax.keyword 6.70",
  "bgElev.syntax.comment 5.32",
  "bgElev.syntax.key 5.25",
  "bgElev.syntax.type 5.01",
  "bgElev.syntax.function 2.44",
  "diffAdd.syntax.keyword 1.64",
  "diffAdd.syntax.string 3.74",
  "diffAdd.syntax.comment 1.30",
  "diffAdd.syntax.number 4.78",
  "diffAdd.syntax.key 1.28",
  "diffAdd.syntax.type 1.22",
  "diffAdd.syntax.function 1.67",
  "diffAdd.syntax.operator 4.10",
  "diffAdd.syntax.punctuation 5.14",
  "diffAdd.tone.ok 3.74",
  "diffAdd.tone.error 1.28",
  "diffAdd.tone.muted 1.30",
  "diffRemove.syntax.keyword 3.49",
  "diffRemove.syntax.comment 2.77",
  "diffRemove.syntax.key 2.74",
  "diffRemove.syntax.type 2.61",
  "diffRemove.syntax.function 1.27",
  "diffRemove.tone.error 2.74",
  "diffRemove.tone.muted 2.77",
  "bgDeep.tone.meta 2.23",
  "bg.categorical.c5 2.44",
  "bgElev.categorical.c5 2.44",
];

/** hcLight. */
const FOUR_HCLIGHT: readonly string[] = [
  "bg.tone.dim 3.95",
  "bg.tone.muted 3.95",
  "bg.tone.ok 5.14",
  "bg.tone.warn 4.20",
  "bg.tone.identifier 4.77",
  "bg.syntax.string 5.14",
  "bg.syntax.comment 3.95",
  "bg.syntax.number 4.20",
  "bg.syntax.type 4.20",
  "bg.syntax.operator 4.77",
  "bgElev.tone.dim 3.95",
  "bgElev.tone.muted 3.95",
  "bgElev.tone.ok 5.14",
  "bgElev.tone.warn 4.20",
  "bgElev.tone.identifier 4.77",
  "bgElev.syntax.string 5.14",
  "bgElev.syntax.comment 3.95",
  "bgElev.syntax.number 4.20",
  "bgElev.syntax.type 4.20",
  "bgElev.syntax.operator 4.77",
  "diffAdd.syntax.keyword 1.83",
  "diffAdd.syntax.string 1.00",
  "diffAdd.syntax.comment 1.30",
  "diffAdd.syntax.number 1.22",
  "diffAdd.syntax.key 2.13",
  "diffAdd.syntax.type 1.22",
  "diffAdd.syntax.function 3.12",
  "diffAdd.syntax.operator 1.08",
  "diffAdd.syntax.punctuation 4.09",
  "diffAdd.tone.ok 1.00",
  "diffAdd.tone.error 2.13",
  "diffAdd.tone.muted 1.30",
  "diffRemove.syntax.keyword 1.16",
  "diffRemove.syntax.string 2.13",
  "diffRemove.syntax.comment 2.77",
  "diffRemove.syntax.number 2.61",
  "diffRemove.syntax.key 1.00",
  "diffRemove.syntax.type 2.61",
  "diffRemove.syntax.function 1.46",
  "diffRemove.syntax.operator 2.29",
  "diffRemove.syntax.punctuation 1.92",
  "diffRemove.tone.ok 2.13",
  "diffRemove.tone.error 1.00",
  "diffRemove.tone.muted 2.77",
  "bgDeep.tone.dim 3.95",
  "bg.categorical.c1 4.20",
  "bg.categorical.c7 3.14",
  "bg.categorical.c8 3.95",
  "bgElev.categorical.c1 4.20",
  "bgElev.categorical.c7 3.14",
  "bgElev.categorical.c8 3.95",
];

/** At 4 bits against the reference palette, per theme — one list per map. */
export const FOUR_BIT_SHORTFALLS: Readonly<Record<string, readonly string[]>> = {
dark: FOUR_DARK,
  ink: FOUR_DARK,
  warm: FOUR_DARK,
  nord: FOUR_DARK,
  viol: FOUR_DARK,
  mono: FOUR_DARK,
  light: FOUR_LIGHT,
  paper: FOUR_LIGHT,
  hcDark: FOUR_HCDARK,
  hcLight: FOUR_HCLIGHT,
};
