// C10 I68 — the quantised shortfalls, recorded when I68 landed and held by
// equality in T2.74 and T2.75. Each entry is `<ground>.<palette>.<slot>` (or
// `hueBand.<name>`) and the ratio to two places.
//
// **The two lists mean different things.** At 8 bits the cube's RGB is fixed,
// so every entry was a defect, owed — and I69 paid it: the list is empty, and a
// line coming back is a regression. At 4 bits the ratios are against the
// reference palette (`ANSI16_WINDOWS_HEX`), because a terminal's low sixteen
// are the user's, so the list is an exemption list in T2.64's shape.
//
// **Not generated, on purpose**: a list written by the function it checks
// agrees with it by construction. It was read out once, when the row landed,
// and checked against an independent probe that found the same 193 and 403
// cells; it changes only by an edit someone reads.

/**
 * At 8 bits, per theme — **empty since C10 I69**, and held empty by equality.
 * 193 entries when I68 landed, in three shapes: `hcDark`'s focus ground (19),
 * two hue bands (7) and 167 inks. I69 held the floor in the quantiser and every
 * line left here; the lists stay, one per theme, so a theme added with no list
 * or a cell that comes back fails T2.74 by name.
 */
export const EIGHT_BIT_SHORTFALLS: Readonly<Record<string, readonly string[]>> = {
  dark: [],
  light: [],
  hcDark: [],
  hcLight: [],
  ink: [],
  warm: [],
  nord: [],
  viol: [],
  mono: [],
  paper: [],
};

/** dark, ink, warm, nord, viol, mono. */
const FOUR_DARK: readonly string[] = [
  "bg.tone.identifier 4.40",
  "bg.syntax.function 2.44",
  "bgElev.tone.identifier 4.40",
  "bgElev.syntax.function 2.44",
  "focusGround.tone.identifier 4.40",
  "focusGround.syntax.function 2.44",
  "diffAdd.syntax.keyword 1.64",
  "diffAdd.syntax.string 3.74",
  "diffAdd.syntax.comment 1.30",
  "diffAdd.syntax.number 1.22",
  "diffAdd.syntax.key 1.28",
  "diffAdd.syntax.function 1.67",
  "diffAdd.syntax.operator 4.10",
  "diffAdd.syntax.punctuation 2.82",
  "diffAdd.tone.ok 3.74",
  "diffAdd.tone.error 1.28",
  "diffAdd.tone.muted 1.30",
  "diffRemove.syntax.keyword 3.49",
  "diffRemove.syntax.comment 2.77",
  "diffRemove.syntax.number 2.61",
  "diffRemove.syntax.key 2.74",
  "diffRemove.syntax.function 1.27",
  "diffRemove.tone.error 2.74",
  "bg.categorical.c2 4.40",
  "bg.categorical.c3 4.09",
  "bg.categorical.c5 2.44",
  "bg.categorical.c6 1.92",
  "bg.categorical.c7 2.23",
  "bgElev.categorical.c2 4.40",
  "bgElev.categorical.c3 4.09",
  "bgElev.categorical.c5 2.44",
  "bgElev.categorical.c6 1.92",
  "bgElev.categorical.c7 2.23",
  "focusGround.categorical.c2 4.40",
  "focusGround.categorical.c3 4.09",
  "focusGround.categorical.c5 2.44",
  "focusGround.categorical.c6 1.92",
  "focusGround.categorical.c7 2.23",
];

/** light, paper. */
const FOUR_LIGHT: readonly string[] = [
  "bg.tone.warn 4.20",
  "bg.syntax.number 4.20",
  "bg.syntax.type 4.20",
  "bgElev.tone.warn 4.20",
  "bgElev.syntax.number 4.20",
  "bgElev.syntax.type 4.20",
  "focusGround.tone.warn 4.20",
  "focusGround.syntax.number 4.20",
  "focusGround.syntax.type 4.20",
  "diffAdd.syntax.keyword 1.83",
  "diffAdd.syntax.string 1.00",
  "diffAdd.syntax.comment 1.30",
  "diffAdd.syntax.number 1.22",
  "diffAdd.syntax.key 2.13",
  "diffAdd.syntax.type 1.22",
  "diffAdd.syntax.function 3.12",
  "diffAdd.syntax.operator 1.08",
  "diffAdd.syntax.punctuation 4.09",
  "diffAdd.tone.ok 1.00",
  "diffAdd.tone.error 2.13",
  "diffAdd.tone.muted 1.30",
  "diffRemove.syntax.keyword 1.16",
  "diffRemove.syntax.string 2.13",
  "diffRemove.syntax.comment 2.77",
  "diffRemove.syntax.number 2.61",
  "diffRemove.syntax.key 1.00",
  "diffRemove.syntax.type 2.61",
  "diffRemove.syntax.function 1.46",
  "diffRemove.syntax.operator 2.29",
  "diffRemove.syntax.punctuation 1.92",
  "diffRemove.tone.ok 2.13",
  "diffRemove.tone.error 1.00",
  "bg.categorical.c1 4.20",
  "bg.categorical.c7 3.14",
  "bg.categorical.c8 3.95",
  "bgElev.categorical.c1 4.20",
  "bgElev.categorical.c7 3.14",
  "bgElev.categorical.c8 3.95",
  "focusGround.categorical.c1 4.20",
  "focusGround.categorical.c7 3.14",
  "focusGround.categorical.c8 3.95",
];

/** hcDark. */
const FOUR_HCDARK: readonly string[] = [
  "bg.tone.muted 5.32",
  "bg.tone.error 5.25",
  "bg.tone.accent 6.70",
  "bg.tone.meta 2.23",
  "bg.tone.identifier 4.40",
  "bg.syntax.keyword 6.70",
  "bg.syntax.comment 5.32",
  "bg.syntax.key 5.25",
  "bg.syntax.type 5.01",
  "bg.syntax.function 2.44",
  "bgElev.tone.muted 5.32",
  "bgElev.tone.error 5.25",
  "bgElev.tone.accent 6.70",
  "bgElev.tone.meta 2.23",
  "bgElev.tone.identifier 4.40",
  "bgElev.syntax.keyword 6.70",
  "bgElev.syntax.comment 5.32",
  "bgElev.syntax.key 5.25",
  "bgElev.syntax.type 5.01",
  "bgElev.syntax.function 2.44",
  "diffAdd.syntax.keyword 1.64",
  "diffAdd.syntax.string 3.74",
  "diffAdd.syntax.comment 1.30",
  "diffAdd.syntax.number 4.78",
  "diffAdd.syntax.key 1.28",
  "diffAdd.syntax.type 1.22",
  "diffAdd.syntax.function 1.67",
  "diffAdd.syntax.operator 4.10",
  "diffAdd.syntax.punctuation 5.14",
  "diffAdd.tone.ok 3.74",
  "diffAdd.tone.error 1.28",
  "diffAdd.tone.muted 1.30",
  "diffRemove.syntax.keyword 3.49",
  "diffRemove.syntax.comment 2.77",
  "diffRemove.syntax.key 2.74",
  "diffRemove.syntax.type 2.61",
  "diffRemove.syntax.function 1.27",
  "diffRemove.tone.error 2.74",
  "diffRemove.tone.muted 2.77",
  "bgDeep.tone.meta 2.23",
  "bg.categorical.c5 2.44",
  "bgElev.categorical.c5 2.44",
];

/** hcLight. */
const FOUR_HCLIGHT: readonly string[] = [
  "bg.tone.dim 3.95",
  "bg.tone.muted 3.95",
  "bg.tone.ok 5.14",
  "bg.tone.warn 4.20",
  "bg.tone.identifier 4.77",
  "bg.syntax.string 5.14",
  "bg.syntax.comment 3.95",
  "bg.syntax.number 4.20",
  "bg.syntax.type 4.20",
  "bg.syntax.operator 4.77",
  "bgElev.tone.dim 3.95",
  "bgElev.tone.muted 3.95",
  "bgElev.tone.ok 5.14",
  "bgElev.tone.warn 4.20",
  "bgElev.tone.identifier 4.77",
  "bgElev.syntax.string 5.14",
  "bgElev.syntax.comment 3.95",
  "bgElev.syntax.number 4.20",
  "bgElev.syntax.type 4.20",
  "bgElev.syntax.operator 4.77",
  "diffAdd.syntax.keyword 1.83",
  "diffAdd.syntax.string 1.00",
  "diffAdd.syntax.comment 1.30",
  "diffAdd.syntax.number 1.22",
  "diffAdd.syntax.key 2.13",
  "diffAdd.syntax.type 1.22",
  "diffAdd.syntax.function 3.12",
  "diffAdd.syntax.operator 1.08",
  "diffAdd.syntax.punctuation 4.09",
  "diffAdd.tone.ok 1.00",
  "diffAdd.tone.error 2.13",
  "diffAdd.tone.muted 1.30",
  "diffRemove.syntax.keyword 1.16",
  "diffRemove.syntax.string 2.13",
  "diffRemove.syntax.comment 2.77",
  "diffRemove.syntax.number 2.61",
  "diffRemove.syntax.key 1.00",
  "diffRemove.syntax.type 2.61",
  "diffRemove.syntax.function 1.46",
  "diffRemove.syntax.operator 2.29",
  "diffRemove.syntax.punctuation 1.92",
  "diffRemove.tone.ok 2.13",
  "diffRemove.tone.error 1.00",
  "diffRemove.tone.muted 2.77",
  "bgDeep.tone.dim 3.95",
  "bg.categorical.c1 4.20",
  "bg.categorical.c7 3.14",
  "bg.categorical.c8 3.95",
  "bgElev.categorical.c1 4.20",
  "bgElev.categorical.c7 3.14",
  "bgElev.categorical.c8 3.95",
];

/** At 4 bits against the reference palette, per theme — one list per map. */
export const FOUR_BIT_SHORTFALLS: Readonly<Record<string, readonly string[]>> = {
dark: FOUR_DARK,
  ink: FOUR_DARK,
  warm: FOUR_DARK,
  nord: FOUR_DARK,
  viol: FOUR_DARK,
  mono: FOUR_DARK,
  light: FOUR_LIGHT,
  paper: FOUR_LIGHT,
  hcDark: FOUR_HCDARK,
  hcLight: FOUR_HCLIGHT,
};
