/**
 * `registry-bindings.ts`, generated from the design registry (C16 §6b, I42,
 * R-KEY-007).
 *
 * **Why a generator rather than a gate.** M6 landed the chords hand-written in
 * `defaultKeymap` beside a rule that compared them to the registry, which is two
 * records of one fact: the gate catches drift after it happens and makes the
 * second copy look deliberate. The chord is the registry's, so it is written
 * there and nowhere else.
 *
 * **What this does not generate, and the reason is R-KEY-003.** Nine registry
 * bindings are one verb several owners spell differently — `escape` is
 * `dismiss`, `exitNativeSelection`, `focusPrompt` — so there is no handler to look up
 * by `actionId`. `when: "focused"` is the design saying the owner decides. That
 * mapping lives in `keymap.ts` as `OWNER_ACTIONS` and is joined to this, never
 * copied from it.
 *
 * Usage: `node tools/generate-keymap.mjs` writes; `--check` compares and exits 1
 * on a difference, which is T1.95.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const REGISTRY = join(ROOT, "docs/design/language/calcium-registry.json");
const OUT = join(ROOT, "src/interaction/router/registry-bindings.ts");

/**
 * The chord spellings that are not a single character.
 *
 * `⌫` is `backspace` rather than `delete`: the tree distinguishes them and
 * `queue.drop`'s `⌥⌫` is the leftward one.
 */
const NAMED = Object.freeze({
  "⏎": "enter", esc: "escape", "⇥": "tab", "↑": "up", "↓": "down",
  "←": "left", "→": "right", "⌫": "backspace", F1: "f1", "?": "?",
});

const MODIFIERS = Object.freeze({ "⌃": "ctrl", "⌥": "meta", "⌘": "super", "⇧": "shift" });

/**
 * A chord to a `Key`, or `null` when this cannot spell it.
 *
 * **`⌥⇧C` is `{name: "C", meta: true}` and carries no shift bit** (C16 I17, C16 T2.13b).
 * `ESC C` names the *character*; a terminal sending it reports no shift, so a
 * binding written `meta+shift+c` is one no event can produce. The shift is spent
 * on the capital and not kept as a flag — which is why this arm is explicit
 * rather than falling out of the loop above it.
 */
export function parseChord(chord) {
  let rest = chord;
  const mods = {};
  for (;;) {
    const mod = MODIFIERS[rest.slice(0, 1)];
    if (mod === undefined) break;
    mods[mod] = true;
    rest = rest.slice(1);
  }
  const named = NAMED[rest];
  if (named !== undefined) return { name: named, ...mods };
  if ([...rest].length !== 1) return null;
  if (mods.shift === true && mods.meta === true && /^[A-Za-z]$/u.test(rest)) {
    const { shift: _spent, ...rest2 } = mods;
    return { name: rest.toUpperCase(), ...rest2 };
  }
  return { name: rest.toLowerCase(), ...mods };
}

const KEY_ORDER = ["name", "ctrl", "meta", "shift", "super"];

const keyLiteral = (key) =>
  `{ ${KEY_ORDER.filter((k) => key[k] !== undefined)
    .map((k) => `${k}: ${JSON.stringify(key[k])}`)
    .join(", ")} }`;

export function generate() {
  const registry = JSON.parse(readFileSync(REGISTRY, "utf8"));
  const rows = [];
  for (const b of registry.bindings) {
    if (b.kind !== "key" || b.status !== "current") continue;
    const key = parseChord(b.chord);
    if (key === null) throw new Error(`${b.id}: cannot spell ${JSON.stringify(b.chord)} as a Key`);
    rows.push({ id: b.id, actionId: b.actionId, chord: b.chord, key, scope: b.scope,
                profile: b.profile, when: b.when });
  }
  rows.sort((a, b) => a.id.localeCompare(b.id));

  // **Only what a consumer reads.** The chord's own spelling, the design's scope
  // and its `when` stay in `calcium-registry.json`: emitting them here would be
  // the second record §6b exists to remove, with a generator's name on it. MG24
  // says the same thing from the other end — a published member nothing consumes
  // is a seam with nothing on the far side. The human-readable chord for a
  // reader of this file is `docs/KEYS.md`, generated from the live table.
  const body = rows
    .map((r) =>
      `  { id: ${JSON.stringify(r.id)}, actionId: ${JSON.stringify(r.actionId)}, ` +
      `key: ${keyLiteral(r.key)} },`,
    )
    .join("\n");

  return `/**
 * The design registry's key bindings, as data (C16 §6b, I42, R-KEY-007).
 *
 * **GENERATED by \`tools/generate-keymap.mjs\`. Do not edit.** The chord for a
 * binding the registry names is written in \`calcium-registry.json\` and nowhere
 * else; editing this file by hand restores the two-records state §6b exists to
 * end, and T1.95 fails when it happens.
 *
 * \`actionId\` is the design's verb, not a \`KeyAction\`. Nine of these are one
 * verb several owners spell differently — \`escape\` is \`dismiss\`,
 * \`exitNativeSelection\` and \`focusPrompt\` — so the join to a handler is
 * \`OWNER_ACTIONS\` in \`keymap.ts\`, keyed by \`(actionId, target)\`. That is
 * R-KEY-003's *unless the current owner explicitly captures the action*, and
 * \`when: "focused"\` is the design saying so.
 */

export type RegistryBinding = Readonly<{
  id: string;
  actionId: string;
  key: Readonly<{ name: string; ctrl?: boolean; meta?: boolean; shift?: boolean; super?: boolean }>;
}>;

export const REGISTRY_BINDINGS: readonly RegistryBinding[] = Object.freeze([
${body}
]);
`;
}

const text = generate();
if (process.argv.includes("--check")) {
  const current = readFileSync(OUT, "utf8");
  if (current === text) {
    console.log(`${OUT} — current`);
  } else {
    console.error(`${OUT} — stale. Run \`node tools/generate-keymap.mjs\`.`);
    process.exit(1);
  }
} else {
  writeFileSync(OUT, text);
  const n = (text.match(/^ {2}\{ id:/gmu) ?? []).length;
  console.log(`${OUT} — ${String(n)} bindings`);
}
