// C10 I41 — the shipped set's quantisations, computed once and written as a
// table `quantiseSet` reads before it runs the DP.
//
// **Against `dist/`, so the answer is the shipped code's** (`probes build before
// they measure`). Every shipped theme's surfaces and each of its palettes gets
// an entry keyed by `quantisationKey`, in key order so a regeneration with no
// change is a byte-identical file. T3.73 holds the table to the computation.
import { writeFileSync } from "node:fs";
import { defaultTheme } from "../../dist/index.js";
import { computeQuantisation, quantisationKey } from "../../dist/presentation/theme/quantise.js";

const OUT = new URL("../../src/presentation/theme/quantised.generated.ts", import.meta.url);

const sets = [];
for (const [name, tokens] of Object.entries(defaultTheme)) {
  sets.push({ from: `${name}.surfaces`, slots: tokens.surfaces });
  for (const [palette, spec] of Object.entries(tokens.palettes)) sets.push({ from: `${name}.palettes.${palette}`, slots: spec.slots });
}

const entries = new Map();
for (const { from, slots } of sets) {
  const key = quantisationKey(slots);
  const held = entries.get(key);
  if (held !== undefined) { held.from.push(from); continue; }
  entries.set(key, { from: [from], picks: computeQuantisation(slots) });
}

const rows = [...entries].sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)).map(([key, { from, picks }]) => {
  const body = Object.entries(picks).map(([slot, index]) => `${JSON.stringify(slot)}: ${String(index)}`).join(", ");
  return `  // ${from.join(", ")}\n  ${JSON.stringify(key)}: Object.freeze({ ${body} }),`;
});

const file = `// Generated by \`tools/theme/quantised.mjs\` — do not edit by hand (C10 I41).
// Regenerate with \`make quantised\` after a shipped theme changes; T3.73 is red until you do.
// ${String(entries.size)} sets over ${String(Object.keys(defaultTheme).length)} themes: each theme's surfaces and each of its palettes.
export const QUANTISED: Readonly<Record<string, Readonly<Record<string, number>>>> = Object.freeze({
${rows.join("\n")}
});
`;
writeFileSync(OUT, file);
console.log(`quantised: ${String(entries.size)} sets written to ${OUT.pathname}`);
