/**
 * The design registry's key bindings, as data (C16 §6b, I42, R-KEY-007).
 *
 * **GENERATED by `tools/generate-keymap.mjs`. Do not edit.** The chord for a
 * binding the registry names is written in `calcium-registry.json` and nowhere
 * else; editing this file by hand restores the two-records state §6b exists to
 * end, and T1.95 fails when it happens.
 *
 * `actionId` is the design's verb, not a `KeyAction`. Nine of these are one
 * verb several owners spell differently — `escape` is `dismiss`, `viewPop`,
 * `exitCopyMode` and `focusPrompt` — so the join to a handler is
 * `OWNER_ACTIONS` in `keymap.ts`, keyed by `(actionId, target)`. That is
 * R-KEY-003's *unless the current owner explicitly captures the action*, and
 * `when: "focused"` is the design saying so.
 */

export type RegistryBinding = Readonly<{
  id: string;
  actionId: string;
  key: Readonly<{ name: string; ctrl?: boolean; meta?: boolean; shift?: boolean; super?: boolean }>;
}>;

export const REGISTRY_BINDINGS: readonly RegistryBinding[] = Object.freeze([
  { id: "binding.001", actionId: "confirm", key: { name: "enter" } },
  { id: "binding.002", actionId: "newline", key: { name: "enter", shift: true } },
  { id: "binding.003", actionId: "escape", key: { name: "escape" } },
  { id: "binding.004", actionId: "focus.next", key: { name: "tab" } },
  { id: "binding.005", actionId: "focus.previous", key: { name: "tab", shift: true } },
  { id: "binding.006", actionId: "move.up", key: { name: "up" } },
  { id: "binding.007", actionId: "move.down", key: { name: "down" } },
  { id: "binding.008", actionId: "move.left", key: { name: "left" } },
  { id: "binding.009", actionId: "move.right", key: { name: "right" } },
  { id: "binding.010", actionId: "selection.up", key: { name: "up", shift: true } },
  { id: "binding.011", actionId: "selection.down", key: { name: "down", shift: true } },
  { id: "binding.012", actionId: "selection.left", key: { name: "left", shift: true } },
  { id: "binding.013", actionId: "selection.right", key: { name: "right", shift: true } },
  { id: "binding.014", actionId: "copy", key: { name: "c", ctrl: true, shift: true } },
  { id: "binding.015", actionId: "paste", key: { name: "v", ctrl: true, shift: true } },
  { id: "binding.016", actionId: "interrupt", key: { name: "c", ctrl: true } },
  { id: "binding.017", actionId: "help.f1", key: { name: "f1" } },
  { id: "binding.018", actionId: "help.question", key: { name: "?" } },
  { id: "binding.020", actionId: "agent.next", key: { name: "tab", ctrl: true } },
  { id: "binding.021", actionId: "agent.previous", key: { name: "tab", ctrl: true, shift: true } },
  { id: "binding.022", actionId: "agent.1", key: { name: "1", super: true } },
  { id: "binding.023", actionId: "agent.2", key: { name: "2", super: true } },
  { id: "binding.024", actionId: "agent.3", key: { name: "3", super: true } },
  { id: "binding.025", actionId: "agent.4", key: { name: "4", super: true } },
  { id: "binding.026", actionId: "agent.5", key: { name: "5", super: true } },
  { id: "binding.027", actionId: "agent.6", key: { name: "6", super: true } },
  { id: "binding.028", actionId: "agent.7", key: { name: "7", super: true } },
  { id: "binding.029", actionId: "agent.8", key: { name: "8", super: true } },
  { id: "binding.030", actionId: "agent.9", key: { name: "9", super: true } },
  { id: "binding.031", actionId: "page.up", key: { name: "up", meta: true } },
  { id: "binding.032", actionId: "page.down", key: { name: "down", meta: true } },
  { id: "binding.033", actionId: "transcript.top", key: { name: "up", super: true } },
  { id: "binding.034", actionId: "transcript.bottom", key: { name: "down", super: true } },
  { id: "binding.035", actionId: "posture.cycle", key: { name: "p", meta: true } },
  { id: "binding.036", actionId: "values.toggle", key: { name: "v", meta: true } },
  { id: "binding.037", actionId: "queue.drop", key: { name: "backspace", meta: true } },
  { id: "binding.host-detach", actionId: "host.detach", key: { name: "]", ctrl: true } },
  { id: "binding.host-detach-enhanced", actionId: "host.detach", key: { name: "escape", meta: true } },
  { id: "binding.selection-native", actionId: "selection.native", key: { name: "C", meta: true } },
  { id: "binding.selection-semantic", actionId: "selection.semantic", key: { name: "V", meta: true } },
]);
